### ISSUE TITLE
创建pvc 报Operation cannot be fulfilled on persistentvolumeclaims

### ISSUE THREAD

**Issue by chenshanping** [caoyingjunz/csi-driver-localstorage#211]
pod event：

running PreBind plugin "VolumeBinding": Operation cannot be fulfilled on persistentvolumeclaims "nginx-pvc": the object has been modified; please apply your changes to the latest version and try again

**Comment by chenshanping** [comment]
这个是我yaml文件

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "pixiu-localstorage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nginx-pvc
      containers:
        - name: nginx
          image: registry.cn-shenzhen.aliyuncs.com/jxqwe/base:nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: data

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
```
